services:
  auth: 
    build:
      context: ./auth
      dockerfile: ./cmd/Dockerfile-auth # Dockerfile para el servicio de autenticación
    ports:
      - "8081:8081"
    networks:
      - backend-net
    environment:
      - DATABASE_URL=root:7nc4381c4t@tcp(host.docker.internal:3306)/goMeli?charset=utf8mb4&parseTime=True&loc=Local

  payment: 
    build:
      context: ./payments
      dockerfile: ./cmd/Dockerfile-payment # Dockerfile para el servicio de pagos
    ports:
      - "8080:8080"
    networks:
      - backend-net

networks:
  backend-net: 
    driver: bridge
